### ISSUE TITLE
Add rumble support for the authentication controller on PS4

### ISSUE THREAD

**Issue by matlo** [matlo/GIMX#566]
It should be possible for Xbox 360 / Xbox One.
Not sure if the Hori Pad FPS Plus emulation has rumble.

**Comment by matlo** [comment]
Thanks for reporting.

**Comment by dogtopus** [comment]
I managed to find the pattern: change the fifth byte of the GET_REPORT 0x03 to 0xff enables touchpad, LEDs and rumble. Not sure which one is which, though. Bit 2 seems to be required for the report to show up (and looks like it also enables LED, but it might be actually caused by the bits that I didn't turn off like bit 0)

**Comment by matlo** [comment]
Thanks for the tip!
