### ISSUE TITLE
Remote adapter

### ISSUE THREAD

**Issue by matlo** [matlo/GIMX#648]
Based on the idea here: https://unix.stackexchange.com/questions/561127/socat-multiple-connection-attempts-fail-to-pass-through-serial/561849

It would be nice to have a direct access to the remote adapter. This way the force-feedback commands would be redirected to the client.

**Comment by redion1992** [comment]
Well, I wasn't going to directly ask for this, but if you're willing to look into it, I'd certainly appreciate it.

**Comment by matlo** [comment]
@redion1992 Could you please check if remote adapter feature added in GIMX 8.0 works on your side?

**Comment by redion1992** [comment]
Well, my setup has changed since the original remote adapter discussion. I ended up getting a natively-compatible PS4 wheel (Thrustmaster T-GT), and moved the PS4 accordingly. However, I still have the equipment, and can set up a test on a regular controller to the Xbox One that is still away from the PC. Give me a couple of days and I can try to test this.
